"""Idempotent setup/repair: generate internal secrets, create D1, deploy the Worker, upload secrets to
Cloudflare and GitHub, register the Telegram webhook. Reads/writes the gitignored .env; never prints a
secret value. Needs: wrangler logged in, gh logged in (GH_CLI env var may point to gh.exe).

    python scripts/setup.py
"""
import json
import os
import re
import secrets
import shutil
import subprocess
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ENV, WORKER = ROOT / ".env", ROOT / "worker"
REPO = "raffaeledf9/TrainWatcher"
GENERATED = ("STATE_KEY", "WORKER_SECRET", "TG_SECRET")
WORKER_SECRETS = ("TELEGRAM_TOKEN", "TG_SECRET", "GH_TOKEN", "WORKER_SECRET", "OWNER_CHAT_ID")
GITHUB_SECRETS = ("TELEGRAM_TOKEN", "STATE_KEY", "WORKER_SECRET", "OWNER_CHAT_ID")
NPX = shutil.which("npx") or "npx"
GH = os.environ.get("GH_CLI") or shutil.which("gh") or "gh"


def load_env():
    return {k.strip(): v.strip() for k, v in (l.split("=", 1) for l in ENV.read_text(encoding="utf-8").splitlines()
                                               if "=" in l and not l.lstrip().startswith("#"))}


def ensure_generated(env):
    added = [k for k in GENERATED if not env.get(k)]
    if added:
        with ENV.open("a", encoding="utf-8", newline="\n") as f:
            f.write("# generated by scripts/setup.py\n" + "".join(f"{k}={secrets.token_urlsafe(32)}\n" for k in added))
    print("generated secrets:", added or "none needed")
    return load_env()


def run(cmd, cwd=ROOT, stdin=None, check=True):
    p = subprocess.run(cmd, cwd=cwd, input=stdin, capture_output=True, text=True, encoding="utf-8")
    if check and p.returncode:
        raise SystemExit(f"command failed ({p.returncode}): {' '.join(cmd[:4])} ... {p.stderr[-400:]}")
    return p.stdout


def ensure_d1():
    toml = (WORKER / "wrangler.toml").read_text(encoding="utf-8")
    dbs = json.loads(run([NPX, "wrangler", "d1", "list", "--json"], cwd=WORKER))
    db = next((d for d in dbs if d["name"] == "trainwatcher"), None)
    if not db:
        run([NPX, "wrangler", "d1", "create", "trainwatcher"], cwd=WORKER)
        db = next(d for d in json.loads(run([NPX, "wrangler", "d1", "list", "--json"], cwd=WORKER)) if d["name"] == "trainwatcher")
    toml = re.sub(r'database_id = "[^"]*"', f'database_id = "{db["uuid"]}"', toml)
    (WORKER / "wrangler.toml").write_text(toml, encoding="utf-8", newline="\n")
    run([NPX, "wrangler", "d1", "execute", "trainwatcher", "--remote", "--file=schema.sql", "--yes"], cwd=WORKER)
    print("d1: ready, schema applied")


def deploy():
    out = run([NPX, "wrangler", "deploy"], cwd=WORKER)
    url = re.search(r"https://trainwatcher\.[a-z0-9-]+\.workers\.dev", out).group(0)
    print("worker deployed:", url)
    return url


def upload(env, url):
    for k in WORKER_SECRETS:
        run([NPX, "wrangler", "secret", "put", k], cwd=WORKER, stdin=env[k])
    print("worker secrets set:", len(WORKER_SECRETS))
    for k in GITHUB_SECRETS:
        run([GH, "secret", "set", k, "-R", REPO], stdin=env[k])
    run([GH, "variable", "set", "WORKER_URL", "-R", REPO, "--body", url])
    print("github secrets set:", len(GITHUB_SECRETS), "+ variable WORKER_URL")


def webhook(env, url):
    body = {"url": url + "/tg", "secret_token": env["TG_SECRET"], "allowed_updates": ["message", "callback_query"], "drop_pending_updates": True}
    req = urllib.request.Request(f"https://api.telegram.org/bot{env['TELEGRAM_TOKEN']}/setWebhook", json.dumps(body).encode(),
                                 {"Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=30) as r:
        print("telegram webhook:", "ok" if json.load(r).get("ok") else "FAILED")


def main():
    env = ensure_generated(load_env())
    missing = [k for k in ("TELEGRAM_TOKEN", "OWNER_CHAT_ID", "GH_TOKEN") if not env.get(k)]
    if missing:
        raise SystemExit(f"fill these in .env first: {missing}")
    ensure_d1()
    url = deploy()
    upload(env, url)
    webhook(env, url)
    return 0


if __name__ == "__main__":
    sys.exit(main())
