"""Helper for scripts/setup.sh. Reads/writes the gitignored .env and never prints a secret except to a
pipe when explicitly asked (`value`), which setup.sh feeds straight into wrangler/gh.

    python scripts/setup.py gen            # add missing internal secrets to .env
    python scripts/setup.py check          # list which required keys are present (names only)
    python scripts/setup.py value NAME     # print one value to stdout (pipe only!)
    python scripts/setup.py d1-id UUID     # write the D1 id into worker/wrangler.toml
    python scripts/setup.py webhook URL    # register the Telegram webhook at URL/tg
"""
import json
import re
import secrets
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ENV = ROOT / ".env"
GENERATED = ("STATE_KEY", "WORKER_SECRET", "TG_SECRET")
REQUIRED = ("TELEGRAM_TOKEN", "OWNER_CHAT_ID", "GH_TOKEN") + GENERATED


def load_env():
    return {k.strip(): v.strip() for k, v in (l.split("=", 1) for l in ENV.read_text(encoding="utf-8").splitlines()
                                               if "=" in l and not l.lstrip().startswith("#"))}


def main(argv):
    cmd, env = argv[0], load_env()
    if cmd == "gen":
        added = [k for k in GENERATED if not env.get(k)]
        if added:
            with ENV.open("a", encoding="utf-8", newline="\n") as f:
                f.write("# generated by scripts/setup.py\n" + "".join(f"{k}={secrets.token_urlsafe(32)}\n" for k in added))
        print("generated:", added or "none needed")
    elif cmd == "check":
        missing = [k for k in REQUIRED if not env.get(k)]
        print("missing:", missing or "none")
        return 1 if missing else 0
    elif cmd == "value":
        sys.stdout.write(env[argv[1]])
    elif cmd == "d1-id":
        p = ROOT / "worker" / "wrangler.toml"
        p.write_text(re.sub(r'database_id = "[^"]*"', f'database_id = "{argv[1]}"', p.read_text(encoding="utf-8")), encoding="utf-8", newline="\n")
        print("wrangler.toml: d1 id set")
    elif cmd == "webhook":
        body = {"url": argv[1].rstrip("/") + "/tg", "secret_token": env["TG_SECRET"], "allowed_updates": ["message", "callback_query"],
                "drop_pending_updates": True}
        req = urllib.request.Request(f"https://api.telegram.org/bot{env['TELEGRAM_TOKEN']}/setWebhook", json.dumps(body).encode(),
                                     {"Content-Type": "application/json"})
        with urllib.request.urlopen(req, timeout=30) as r:
            ok = json.load(r).get("ok")
        print("telegram webhook:", "ok" if ok else "FAILED")
        return 0 if ok else 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
