"""Station catalogue: webapp/stations.json, generated by scripts/build_stations.py.

The Mini App sends an entry's key; the job resolves it to operator ids here. Free text is never
resolved at run time (lefrecce name search is unreliable); the form matches names itself.
Entry: {"k": key, "n": name, "t": lefrecce id|None, "i": Italo code|None, "g": 1 if city group, "a": abbr}.
"""
import json
from functools import cache
from pathlib import Path

from trainwatcher.offers import ITALO, TRENITALIA

PATH = Path(__file__).resolve().parent.parent / "webapp" / "stations.json"


@cache
def _index():
    return {e["k"]: e for e in json.loads(PATH.read_text(encoding="utf-8"))}


def entries():
    return list(_index().values())


def by_key(k):
    """The entry for a key; KeyError if the catalogue has no such key."""
    return _index()[k]


def operator_ids(entry):
    """{operator: id} for the operators serving this entry; an operator without an id is skipped."""
    return {op: v for op, v in ((TRENITALIA, entry["t"]), (ITALO, entry["i"])) if v}


def abbreviation(entry):
    return entry["a"]


def serves(key, op):
    """True if operator op ("T" or "I") stops at the catalogue entry key."""
    e = _index().get(key) or {}
    return bool(e.get("t" if op == "T" else "i"))


def display_name(raw):
    """Name of a station as an operator returns it in results: Italo gives codes (MC_), Trenitalia names."""
    return next((e["n"] for e in entries() if e.get("i") == raw and not e.get("g")), raw)
